analyzer:
  errors:
    invalid_assignment: error
    missing_return: error
    dead_code: error
    unused_local_variable: false
    unused_import: false

linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
    - always_declare_return_types
    - annotate_overrides
    - avoid_init_to_null
    - sort_constructors_first
#    - slash_for_doc_comments

