name: "unification"
version: "0.1.6"
author: "Michael Bürgerling <michael.buergerling@gmail.com>"
description: "Unification is an implementation of logical first-order unification. It follows Robinson's algorithm, and uses trampolining to avoid stack size limitation issues."
homepage: "https://github.com/welopment/unification"
environment:
  sdk: '>=1.8.0 <3.0.0'

dependencies:
  #tailcalls: ^0.1.1
  tailcalls: 
    path: ../tailcall

dev_dependencies:
  test: '1.6.3' 
  pedantic: ^1.0.0
