name: "unification"
version: "0.1.8"
author: "Michael Bürgerling <michael.buergerling@gmail.com>"
description: "An implementation of logical first-order unification."
homepage: "https://github.com/welopment/unification"
environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  tailcalls:
  #tailcalls:
  #  path: ../tailcall
  trampoline:
    path: ../trampoline

dev_dependencies:
  #test: ^1.6.3
  pedantic: ^1.0.0
